### ISSUE TITLE
Foreign key ref failer

### ISSUE THREAD

**Issue by jarensaa** [finnss/database-prosjekt#1]
Første gang man kjører create_tables.py etter opprettelse av databasen så klager programmet på at foreign key ref ikke er mulig. 

Den prøver å lage foreign key relationships med tabeller som enda ikke eksisterer.

**Comment by finnss** [comment]
Jepp, jeg er klar over det, det er den buggen jeg snakket om. Jeg tror ikke problemet er at tabellen ikke eksisterer: For det første ligger kodeblokken som failer under blokken som lager tabellen som refereres. For det andre har jeg prøvd å kjøre koden mens resten av tabellene allerede var laget, og man får fortsatt samme feil. Jeg sliter skikkelig med å se hva som er feil; jeg har prøvd å slette forskjellige linjer og flytte rundt på ting og mye annet. Dette er en aktuelle kodeblokken:

```
TABLES['mål'] = (
"	CREATE TABLE `mål`("
"	  `målid`        int(10) NOT NULL,"
"	  `tidsfrist`    date,"
"	  `repetisjoner` int(10),"
"	  `sett`         int(10),"
"	  `vekt`         int(10),"
"	  `lengde`       varchar(10),"
"	  `kommentar`    varchar(200),"
"	  CONSTRAINT `mål_PK` PRIMARY KEY (`målid`),"
"	  CONSTRAINT `brukernavn_FK` FOREIGN KEY (`brukernavn`) REFERENCES `bruker`(`brukernavn`)"
"	                                                      ON UPDATE CASCADE"
"	                                                      ON DELETE CASCADE,"
"	  CONSTRAINT `øvelse_FK` FOREIGN KEY(`øvelse_navn`) REFERENCES `øvelse`(`øvelse_navn`)"
"	                                                      ON UPDATE CASCADE"
"	                                                      ON DELETE CASCADE"
"	) ENGINE=InnoDB")
```

Hvis du åpner python-filen vil du se at alle variabelnavn inni paranteser, som `FOREIGN KEY('øvelse_navn')`, blir lilla. Men i den problematiske blokken blir de *ikke* lilla, så selv PyCharm skjønner at det er en gal referanse på en eller annen måte. Hvis dere skjønner hva som er feil er det bare å skrike ut.

**Comment by jarensaa** [comment]
Problemer er at relasjonene blir opprettet før entitetene, så foreign key refererer til keys som ikke eksisterer.  Det funker nemlig når man kjører koden for andre gang.

**Comment by finnss** [comment]
For meg funket det ikke når man kjørte koden for andre gang. Problemet var at det ikke var noen felt for `brukernavn` eller `øvelse_navn` i selve mål-tabellen! Du hadde fikset det i branchen din, så jeg stjal svaret derfra, takk 😄 Fikset i #4.
