### ISSUE TITLE
Treningsøkt har brukerid?

### ISSUE THREAD

**Issue by finnss** [finnss/database-prosjekt#6]
SQL-koden @spreede skrev til `Treningsøkt` var som følger:

```
CREATE TABLE treningsøkt(
  øktid              INTEGER NOT NULL,
  brukerid           INTEGER NOT NULL,
  tidspunkt          DATETIME,
  idrett             VARCHAR(20),
CONSTRAINT treningsøkt_PK PRIMARY KEY (øktid),
);
```

Den konverterte jeg til Python-kode. Men hva er egentlig `brukerid`? Den er ikke inkludert i ER-diagrammet: 
<img width="166" alt="skjermbilde 2017-03-15 kl 15 15 45" src="https://cloud.githubusercontent.com/assets/14221386/23952646/560153d0-0992-11e7-8b2b-77f9d20d207a.png">

Det er vel `har trent` som holder styr på forholdet mellom Bruker og Treningsøkt?

**Comment by simehag** [comment]
brukerid er brukt feil. Bare å fjerne den. :/

**Comment by finnss** [comment]
Fikses i #5
